
--Inserções da tabela Entrevistas
INSERT INTO entrevistas (titulo, descricao, url_entrevista, id_professor) 
VALUES 
('Como conciliar os estudos com a rotina?', 'Como conciliar os estudos com a rotina" sugere um conteúdo focado em estratégias para equilibrar os estudos com outras atividades diárias, como trabalho, lazer e cuidados pessoais. A entrevista destaca dicas de gestão de tempo, organização, foco e como evitar sobrecarga, mantendo uma rotina produtiva e saudável. Este tipo de orientação é essencial para quem busca otimizar o aprendizado sem comprometer o bem-estar.', 'https://www.youtube.com/watch?v=pl-u54kw3Q8', 1),
('Temas mais cobrados nos vestibulares', 'Temas mais cobrados nos vestibulares" indica um conteúdo que aborda as matérias e assuntos que têm maior incidência nas provas de vestibular. A entrevista destaca as áreas de maior relevância, como atualidades, matemática, linguagens, ciências humanas e naturais, além de sugestões de como se preparar para essas questões específicas. O foco é orientar os candidatos a priorizar os temas que mais aparecem, aumentando suas chances de sucesso nas provas.', 'https://www.youtube.com/watch?v=V7dKkVg3En4', 1),
('Como funciona os estudos da biologia?', 'Como funciona os estudos da biologia?" sugere um conteúdo explicativo sobre os métodos e abordagens para estudar biologia de forma eficaz. A entrevista explica aspectos como a importância de entender os conceitos fundamentais, como células, genética e ecologia, além de estratégias de aprendizado como a utilização de diagramas, revisões periódicas e a prática de exercícios. O objetivo é ajudar os estudantes a organizar seus estudos e a dominar os tópicos essenciais dessa disciplina científica.', 'https://www.youtube.com/watch?v=zHLGaZtg-wo', 1);

--Inserções da tabela Aulas

INSERT INTO aulas (titulo, descricao, url_aula, id_professor) 
VALUES 
('Introdução à Biologia', 'Nessa videoaula de introdução à biologia, o professor Paulo Jubilut explica o que a Biologia estuda. Além disso, você irá aprender que a ciência da vida possui várias especialidades como a ecologia, bioquímica, citologia, genética, embriologia, fisiologia, botânica, biotecnologia e zoologia. Aprenda ainda a diferença entre o que é ciência e o que é tecnologia.', 'https://www.youtube.com/watch?v=t-gZtyd3RgI', 2),
('As doenças que mais caem no ENEM', 'A compreensão dos principais tipos de doenças, suas causas, consequências e formas de prevenção é essencial não apenas para o desempenho no ENEM, mas também para o entendimento da realidade atual em termos de saúde pública. Este video aborda as doenças que mais frequentemente aparecem nas questões do ENEM, destacando a importância de sua abordagem no contexto do exame e da educação em saúde.', 'https://www.youtube.com/watch?v=nc2Z5e85x7o', 2),
('Células-Tronco, Clonagem, Transgênicos e Teste de DNA - Revisão ENEM Biologia', 'No contexto do Exame Nacional do Ensino Médio (ENEM), temas relacionados à biotecnologia e avanços científicos, como células-tronco, clonagem, transgênicos e testes de DNA, são frequentemente abordados nas questões de Biologia. Esses tópicos envolvem complexos conhecimentos sobre genética, ética e suas aplicações práticas na medicina, na agricultura e em outras áreas da ciência.', 'https://www.youtube.com/watch?v=VYC9v9E9-xQ', 2);
