
--Inserções da tabela Entrevistas
INSERT INTO entrevistas (titulo, descricao, url_entrevista, id_professor) 
VALUES 
('Como conciliar os estudos com a rotina?', ' Nesta entrevista é abordada estratégias para equilibrar os estudos com outras atividades diárias, como trabalho, lazer e cuidados pessoais. A professora Eva destaca dicas de gestão de tempo, organização, foco e como evitar sobrecarga, mantendo uma rotina produtiva e saudável. Este tipo de orientação é essencial para quem busca otimizar o aprendizado sem comprometer o bem-estar.', 'https://www.youtube.com/embed/pl-u54kw3Q8?si=zp0P58NyQJ0TYLmw', 1),
('Temas mais cobrados nos vestibulares', 'A entrevista destaca os temas de biologia mais frequentes nos vestibulares, como ecologia, genética, evolução e fisiologia, trazendo dicas práticas de estudo e estratégias para resolver questões. O foco é orientar os alunos a priorizar os temas que mais aparecem, aumentando suas chances de sucesso nas provas.', 'https://www.youtube.com/embed/V7dKkVg3En4?si=IfU4j43YQ5Km1RHP', 1),
('Como funciona os estudos da biologia?', 'A vídeo aula "Introdução à Genética", ministrada pelo professor Paulo Jubilut, é uma explanação essencial sobre os conceitos fundamentais dessa área da Biologia. Com o auxílio de computação gráfica, o professor explica de forma clara e visual os conceitos de dominância, recessividade, genótipo, fenótipo, homozigose e heterozigose. Ele detalha como esses conceitos estão relacionados à hereditariedade e como influenciam a expressão das características nos seres vivos. A aula é uma introdução importante para quem deseja entender os princípios básicos da genética e suas aplicações.', 'https://www.youtube.com/embed/2rqEmRrtkYc?si=uy0wXfu5p4U4fP9x', 1);

--Inserções da tabela Aulas

INSERT INTO aulas (titulo, descricao, url_aula, id_professor) 
VALUES 
('Introdução à Biologia', 'A vídeo aula "Introdução à Genética", ministrada pelo professor Paulo Jubilut, é uma explanação essencial sobre os conceitos fundamentais dessa área da Biologia. Com o auxílio de computação gráfica, o professor explica de forma clara e visual os conceitos de dominância, recessividade, genótipo, fenótipo, homozigose e heterozigose. Ele detalha como esses conceitos estão relacionados à hereditariedade e como influenciam a expressão das características nos seres vivos. A aula é uma introdução importante para quem deseja entender os princípios básicos da genética e suas aplicações.', 'https://www.youtube.com/embed/2rqEmRrtkYc?si=uy0wXfu5p4U4fP9x', 2),
('As doenças que mais caem no ENEM', 'Neste vídeo, o professor Paulo Jubilut aborda as três doenças que mais costumam ser cobradas no ENEM: Doença de Chagas, Esquistossomose e Dengue. Com uma explicação detalhada e acessível, o professor explica as características de cada uma dessas doenças, seus agentes causadores, formas de transmissão, sintomas e medidas de prevenção. Através de exemplos e informações relevantes, a vídeo aula proporciona um entendimento claro sobre o impacto dessas doenças na saúde pública, além de fornecer uma base sólida para os estudantes que se preparam para o exame. ', 'https://www.youtube.com/embed/nc2Z5e85x7o?si=OAsGiFxEpBcQJDN8', 2),
('Células-Tronco, Clonagem, Transgênicos e Teste de DNA - Revisão ENEM Biologia', 'O professor Paulo Jubilut faz uma revisão sobre temas importantes da Biologia, frequentemente cobrados no ENEM, como Células-Tronco, Clonagem, Organismos Transgênicos e Teste de DNA. A aula explica, de forma acessível, os conceitos básicos de cada um desses tópicos, abordando suas implicações científicas, éticas e sociais. O professor detalha o funcionamento das células-tronco, as diferentes formas de clonagem, a produção e os usos de organismos transgênicos, além de esclarecer como os testes de DNA são realizados e suas aplicações. A vídeo aula oferece um resumo completo desses temas, preparando os estudantes para as questões do ENEM e outros vestibulares.', 'https://www.youtube.com/embed/VYC9v9E9-xQ?si=dqlusSi-5plk-uvD', 2);
